-- Q1: For each manager, what is the total revenue generated by their team,
--     including all indirect subordinates?

WITH RECURSIVE employee_hierarchy AS (
  -- Start with each employee as their own root
  SELECT
    EmployeeId,
    ReportsTo,
    EmployeeId AS RootEmployeeId
  FROM Employee

  UNION ALL

  -- Walk down the hierarchy
  SELECT
    e.EmployeeId,
    e.ReportsTo,
    h.RootEmployeeId
  FROM Employee e
  JOIN employee_hierarchy h
    ON e.ReportsTo = h.EmployeeId
),
root_customers AS (
  -- For each root manager, collect customers in their subtree
  SELECT
    h.RootEmployeeId AS ManagerId,
    c.CustomerId
  FROM employee_hierarchy h
  JOIN Customer c
    ON c.SupportRepId = h.EmployeeId
),
root_revenue AS (
  -- Sum revenue for each manager over all subtree customers
  SELECT
    rc.ManagerId,
    SUM(il.UnitPrice * il.Quantity) AS TeamRevenue
  FROM root_customers rc
  JOIN Invoice i
    ON i.CustomerId = rc.CustomerId
  JOIN InvoiceLine il
    ON il.InvoiceId = i.InvoiceId
  GROUP BY rc.ManagerId
)
SELECT
  e.EmployeeId,
  CONCAT(e.FirstName, ' ', e.LastName) AS ManagerName,
  e.Title,
  rr.TeamRevenue
FROM root_revenue rr
JOIN Employee e
  ON e.EmployeeId = rr.ManagerId
ORDER BY rr.TeamRevenue DESC;
