-- Q: What is the total revenue generated by each artist?
-- Purpose: Baseline comparison - show SQL works fine for simple queries
-- Complexity: ⭐ (1/5) - Straightforward multi-table join
-- Expected Result: Top revenue-generating artists
--
-- Demonstrates: SQL's strength with structured joins
-- Pain Points: Still requires 5 explicit JOINs and full table knowledge

SELECT 
  a.ArtistId,
  a.Name AS ArtistName,
  COUNT(DISTINCT t.TrackId) AS TotalTracks,
  SUM(il.UnitPrice * il.Quantity) AS TotalRevenue
FROM Artist a
JOIN Album al ON al.ArtistId = a.ArtistId
JOIN Track t ON t.AlbumId = al.AlbumId
JOIN InvoiceLine il ON il.TrackId = t.TrackId
JOIN Invoice i ON i.InvoiceId = il.InvoiceId
GROUP BY a.ArtistId, a.Name
ORDER BY TotalRevenue DESC
LIMIT 10;

-- Notes for Presentation:
-- ✓ SQL handles this well - 12 lines, clear logic
-- ✗ Must know exact foreign key relationships
-- ✗ Brittle: Schema changes break the query
-- → Compare with SPARQL's property paths
