-- Q2 (SQL solution)
-- For each artist, what is the total revenue generated by their tracks?

SELECT
  a.ArtistId,
  a.Name AS ArtistName,
  SUM(il.UnitPrice * il.Quantity) AS ArtistRevenue
FROM Artist a
JOIN Album al
  ON al.ArtistId = a.ArtistId
JOIN Track t
  ON t.AlbumId = al.AlbumId
JOIN InvoiceLine il
  ON il.TrackId = t.TrackId
JOIN Invoice i
  ON i.InvoiceId = il.InvoiceId
-- (Optional) Join Customer if you want the full path, but it isn't needed for the sum:
-- JOIN Customer c
--   ON c.CustomerId = i.CustomerId
GROUP BY
  a.ArtistId,
  ArtistName
ORDER BY
  ArtistRevenue DESC,
  ArtistName;
