-- Q1: For each manager, what is the total revenue generated by their team,
--     including all indirect employee coordinates?
--
--   Employee.ReportsTo defines a hierarchy.
--   Customers are linked to their support rep (Employee).
--   We want each manager's revenue over ALL employees in their employeetree.
SELECT
  manager.EmployeeId,
  CONCAT(manager.FirstName, ' ', manager.LastName) AS ManagerName,
  manager.Title,
  SUM(il.UnitPrice * il.Quantity) AS TeamRevenue
FROM Employee manager
JOIN Employee employee ON (
  employee.ReportsTo = manager.EmployeeId OR  -- Direct reports
  employee.EmployeeId = manager.EmployeeId OR -- Manager themselves
  employee.ReportsTo IN (                     -- Indirect reports
    SELECT indirectReport.EmployeeId 
    FROM Employee indirectReport 
    WHERE indirectReport.ReportsTo = manager.EmployeeId
  )
)
JOIN Customer c ON c.SupportRepId = employee.EmployeeId
JOIN Invoice i ON i.CustomerId = c.CustomerId
JOIN InvoiceLine il ON il.InvoiceId = i.InvoiceId
GROUP BY manager.EmployeeId, manager.FirstName, manager.LastName, manager.Title
ORDER BY TeamRevenue DESC;