-- Q1: For each customer, what is their favorite genre
--     (the genre where they spent the most money)?
--
-- Goal:
--   Return one row per customer with:
--     - CustomerId
--     - CustomerName
--     - FavoriteGenre
--     - AmountSpentOnFavoriteGenre
--
-- Hints:
--   1) Join: Customer -> Invoice -> InvoiceLine -> Track -> Genre
--   2) Compute revenue per customer & genre:
--        SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity)
--   3) From that result, pick the top genre per customer.
--      In MySQL 8+ you can use:
--        ROW_NUMBER() OVER (PARTITION BY CustomerId ORDER BY GenreRevenue DESC)
--      and then filter rn = 1.
--
-- Write your SQL below:

